### ISSUE TITLE
Keyboard showing comma instead of decimal point

### ISSUE THREAD

**Issue by velkysef** [icon-project/iconex_ios#5]
I can enter only whole numbers, because comma the keyboard shows me is not accepted as decimal mark.

![photo_2018-12-09_18-31-08](https://user-images.githubusercontent.com/5190880/49701090-ff0f2580-fbe7-11e8-8f5b-4586b2cc300e.jpg)

**Comment by a1ahn** [comment]
Fixed in 1.5.1
